### PR TITLE
Update deps + bump react peerDependencies to 18.3.1

### PR DESCRIPTION
**Pull request by MiXeR54**

### CODE REVIEW

**Comment by hiendaovinh** [comment]
Agree, `^18.2.0` should work.

**Comment by MiXeR54** [comment]
Updated.

**Comment by mainsmirnov** [comment]
Something is wrong with `package-lock.json` file. It should contain as well only change of two lines. Try to checkout file to old commit and run `npm install` after

**Comment by MiXeR54** [comment]
Updated.

**Comment by mainsmirnov** [comment]
Thank you for your contribution

**Pull request merged**
