### PR TITLE
Fixes for Snackbar

### PR DESCRIPTION
**Pull request by grulex**
Changed Snackbar position to "fixed" — it works better with scrolling; changed wrapper bottom to 17px, it works better with safe-area

### CODE REVIEW

**Comment by grulex** [comment]
Position: absolute:
https://github.com/Telegram-Mini-Apps/TelegramUI/assets/26435031/85e6107e-e02e-47a0-85fe-62a7b8d35dbf

position: fixed:
https://github.com/Telegram-Mini-Apps/TelegramUI/assets/26435031/b60d4c94-988c-43c0-9df8-54f98b7cac2a

**Comment by grulex** [comment]
Example with `position: absolute`:
https://github.com/Telegram-Mini-Apps/TelegramUI/assets/26435031/777866f2-5532-4e10-8117-660989bb3a6d

Example with `position: fixed`:
https://github.com/Telegram-Mini-Apps/TelegramUI/assets/26435031/f062beef-d96a-458a-9dd3-deea512ea015

**Comment by heyqbnk** [comment]
`position: fixed` may lead to rendering bugs in iOS

**Comment by grulex** [comment]
Maybe we need to add option “source=top/bottom”? 
there will be no problem here if the snack bar appears on top

**Comment by mainsmirnov** [comment]
Position fixed is legit, but why did you change bottom padding from 17 to 10?

**Comment by grulex** [comment]
@mainsmirnov Because 10px is not enough to raise the snackbar enough on iOS, the controls partially overlap it. With the latest changes, the WebApp always opens without the bot chat line, and the SnackBar is superimposed on the control. env(safe-area..) doesn't work yet, always 0px

**Comment by mainsmirnov** [comment]
Let's do it only for iOS. There is class `wrapper--ios` for this purpose. Consider to change it to 16

**Comment by grulex** [comment]
examples with 10px/16px

IMG_0698
IMG_0699

**Comment by mainsmirnov** [comment]
Thank you for your contribution

**Pull request merged**
